### ISSUE TITLE
ElementBarycentreGeneratorPUML

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#49]
Hi,

Any Idea on what could cause such an error?
I m getting the error on the latest energy_output branch + git merge master 
This is more or less a setup which was running without problem in early december.

Thomas.

```cpp
#0  0x00002b3b1211eeaf in waitpid () from /lib64/libc.so.6
#1  0x00002b3b120b2cd1 in do_system () from /lib64/libc.so.6
#2  0x00002b3b120b307c in system () from /lib64/libc.so.6
#3  0x00002b3b1b25b366 in pm_linux_print_coredump () from /opt/ibmhpc/pe1404/base/intel/lib64/libpoe.so
#4  0x00002b3b1b25a8ab in pm_lwcf_signal_handler () from /opt/ibmhpc/pe1404/base/intel/lib64/libpoe.so
#5  <signal handler called>
#6  0x000000000052152c in seissol::initializers::ElementBarycentreGeneratorPUML::generate() const ()
#7  0x000000000052097b in seissol::initializers::ParameterDB::evaluateModel(std::string const&, seissol::initializers::QueryGenerator const&) ()
#8  0x00000000005791b6 in seissol::initializers::time_stepping::LtsWeights::computeWeights(PUML::PUML<(PUML::TopoType)0> const&) ()
#9  0x000000000048a962 in seissol::PUMLReader::PUMLReader(char const*, seissol::initializers::time_stepping::LtsWeights*, double) ()
#10 0x0000000000478e8a in read_mesh_puml_c ()
#11 0x000000000046f8b5 in meshreadercbinding_mp_read_mesh_fast_ ()
#12 0x00000000004a1965 in ini_seissol_mod_mp_ini_seissol_ ()
#13 0x0000000000706187 in fortran_main ()
#14 0x0000000000750709 in main ()

```

**Comment by Thomas-Ulrich** [comment]
Maybe the submodule were not up to date on my repository. It seems to be working now.

**Comment by Thomas-Ulrich** [comment]
I reopen the issue, as I was able to reproduce the issue on a different setup with master branch unmodified. No error with order 3, but error with order 4 and different nodes configurations (6 or 20).

@uphoffc The setup which generates the problem can be found here:
/gpfs/work/pr45fi/di73yeq3/KoreaSetup-bug

**Comment by Thomas-Ulrich** [comment]
Probably related to the bugs on energy-output branch. Therefore I close it is for now.
