### ISSUE TITLE
potential bug related with attenuation?

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#52]
Hi,

There seems to be a bug related with attenuation in SeisSol ( the setup is working when using elasticity  but crushes wwith attenuation).

Here is the error log:
```cpp
#15 0x000000000050d1a5 in deallocate (this=<optimized out>, __p=<optimized out>) at /lrz/mnt/sys.x86_64/compilers/gcc/4.9.3/bin/../include/c++/4.9.3/ext/new_allocator.h:110
#16 deallocate (__a=..., __p=<optimized out>, __n=<optimized out>) at /lrz/mnt/sys.x86_64/compilers/gcc/4.9.3/bin/../include/c++/4.9.3/bits/alloc_traits.h:383
#17 _M_deallocate (this=<optimized out>, __p=0x6e88, __n=<optimized out>) at /lrz/mnt/sys.x86_64/compilers/gcc/4.9.3/bin/../include/c++/4.9.3/bits/stl_vector.h:178
#18 ~_Vector_base (this=<optimized out>) at /lrz/mnt/sys.x86_64/compilers/gcc/4.9.3/bin/../include/c++/4.9.3/bits/stl_vector.h:160
#19 ~_Vector_base (this=<optimized out>) at /lrz/mnt/sys.x86_64/compilers/gcc/4.9.3/bin/../include/c++/4.9.3/bits/stl_vector.h:159
#20 ~vector (this=<optimized out>) at /lrz/mnt/sys.x86_64/compilers/gcc/4.9.3/bin/../include/c++/4.9.3/bits/stl_vector.h:425
#21 ~Vertex (this=<optimized out>) at src/Geometry/MeshDefinition.h:77
#22 _Destroy (__pointer=<optimized out>) at /lrz/mnt/sys.x86_64/compilers/gcc/4.9.3/bin/../include/c++/4.9.3/bits/stl_construct.h:93
#23 __destroy (__first=0x2b6345015260, __last=<optimized out>) at /lrz/mnt/sys.x86_64/compilers/gcc/4.9.3/bin/../include/c++/4.9.3/bits/stl_construct.h:103
#24 _Destroy (__first=<optimized out>, __last=<optimized out>) at /lrz/mnt/sys.x86_64/compilers/gcc/4.9.3/bin/../include/c++/4.9.3/bits/stl_construct.h:126
#25 _Destroy (__first=0x6e88, __last=<optimized out>) at /lrz/mnt/sys.x86_64/compilers/gcc/4.9.3/bin/../include/c++/4.9.3/bits/stl_construct.h:151
#26 ~vector (this=<optimized out>) at /lrz/mnt/sys.x86_64/compilers/gcc/4.9.3/bin/../include/c++/4.9.3/bits/stl_vector.h:424
#27 ~MeshReader (this=<optimized out>) at src/Geometry/MeshReader.h:87
#28 ~MeshReader (this=<optimized out>) at src/Geometry/MeshReader.h:85
#29 ~PUMLReader (this=<optimized out>) at src/Geometry/PUMLReader.h:61
#30 seissol::PUMLReader::~PUMLReader (this=0x6e88) at src/Geometry/PUMLReader.h:61
#31 0x000000000072832d in freeMeshReader (this=<optimized out>) at src/SeisSol.h:233
#32 initializeIO (this=<optimized out>, mu=<optimized out>, slipRate1=<optimized out>, slipRate2=<optimized out>, slip=<optimized out>, slip1=<optimized out>, slip2=<optimized out>, state=<optimized out>, strength=<optimized out>, numSides=<optimized out>, numBndGP=<optimized out>, refinement=<optimized out>, outputMask=<optimized out>, outputRegionBounds=<optimized out>, freeSurfaceInterval=<optimized out>, freeSurfaceFilename=<optimized out>, xdmfWriterBackend=<optimized out>) at src/Solver/Interoperability.cpp:712
#33 c_interoperability_initializeIO (mu=0x6e88, slipRate1=0x6e88, slipRate2=0x6, slip=0xffffffffffffffff, slip1=0x0, slip2=0x0, state=0x2b6365d1af60, strength=0x2b6365d1af20, numSides=0, numBndGP=25, refinement=0, outputMask=0x7ffd219a4c00, outputRegionBounds=0x2b62e715fd00, freeSurfaceInterval=-5.4874582225770505e+303, freeSurfaceFilename=0x7ffd219a4be0 "../output_nepal_att/nepal_test", xdmfWriterBackend=0x7ffd219a4bc0 "hdf5") at src/Solver/Interoperability.cpp:212
#34 0x00000000006aa654 in inioutput_seissol_mod::inioutput_seissol (time=<error reading variable: Cannot access memory at address 0x6e88>, timestep=<error reading variable: Cannot access memory at address 0x6e88>, pvar=<error reading variable: Cannot access memory at address 0x6>, cvar=<error reading variable: Cannot access memory at address 0xffffffffffffffff>, eqn=<error reading variable: Location address is not set.>, ic=<error reading variable: Location address is not set.>, mesh=..., mpi=..., source=..., disc=..., bnd=..., optionalfields=..., io=..., analyse=..., programtitle=..., .tmp.PROGRAMTITLE.len_V$8f71=100) at src/ResultWriter/inioutput_seissol.f90:169
#35 0x0000000000745417 in seissol::main () at src/seissolxx.f90:213
#36 0x000000000078da69 in main (argc=28296, argv=0x6e88) at src/main.cpp:56
```
and the out log:

```cpp
Tue Feb 19 09:14:29, Info:  Initializing free surface output.
Tue Feb 19 09:14:31, Info:  Initializing free surface output. Done.
Rank:        0 | Info    | <--------------------------------------------------------->
Rank:        0 | Info    | <     Start calc_SeisSol ...                              >
Rank:        0 | Info    | <--------------------------------------------------------->
```

I m using the master branch, non-modified.

@uphoffc:
on Supermuc2, the setup is here 
/gpfs/work/pr45fi/di73yeq3/model3

Thomas.

**Comment by uphoffc** [comment]
How many nodes did you use? Did you maybe run out of memory?

**Comment by Thomas-Ulrich** [comment]
20 nodes with o3 or o4, 2.3mio cells.

**Comment by Thomas-Ulrich** [comment]
I rerun on master and it works fine. So it is again related to the 4 commits of the energy output , which are definitely not working with attenuation.
