### ISSUE TITLE
plastCo, bulkFriction easi/SeisSol bug

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#667]
**Describe the bug**
I've been facing again the plastCo, bulkFriction easi/SeisSol bug, and I tried to simplify the setup to get the bug.
The starting setup is training/sulawesi (RS setup).
The only changes are a bigger mesh (Sulawesi_65dip_straightBay_ShortNorth, 1mio cells) and a slightly different material file.
```yaml
!Switch
[rho, mu, lambda]:  !IdentityMap
  #use if defined Awaliah et al.
  #else if defined Fichtner et al.
  #else a constant velocity
  components:
    - !ASAGI
      file: 3dvel_Sulawesi_BMKG.nc
      parameters: [rho, mu, lambda]
      var: data
    - !ASAGI
      file: 3dvel_Sulawesi.nc
      parameters: [rho, mu, lambda]
      var: data
    - !ConstantMap
        map:
         rho: 3330.
         mu: 65942325000.
         lambda: 81235350000.
[plastCo, bulkFriction]: !IdentityMap
  components:
    - !SphericalDomainFilter
      radius: 2.0e3
      centre:
        x:  17700.0
        y: 55580.0
        z: -10000.0
      components: !ConstantMap
        map:
            plastCo: 18400675.295442805
            bulkFriction: 0.8553018383357905
    - !EvalModel
        parameters: [a]
        model: !EvalModel
            parameters: [b]
            model: !ConstantMap
                map:
                  b: 0.0
            components: !ConstantMap
                map:
                    a: -1000.
        components: !ConstantMap
              map:
                plastCo: 18400675.295442805
                bulkFriction: 0.8553018383357905
[s_xx, s_yy, s_zz, s_xy, s_yz, s_xz]: !Include Sulawesi_initial_stressRS.yaml
```
(the material file does not make much sense, but it is the simplest way to reproduce the error)
The setup is here:
/hppfs/work/pr63qo/di73yeq4/Training_bug/sulawesi
(the material file can be parsed with easicube without an error).

run on 16 nodes:
```bash
Mon Sep 05 12:36:03, Info:  Reading mesh. Done. 
Mon Sep 05 12:36:03, Info:  Extracting fault information 
Mon Sep 05 12:36:04, Info:  Mesh initialized in: 14.9241 (min: 14.8697, max: 14.9528)
=================================================================
==3736574==AddressSanitizer CHECK failed: /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/sanitizer_common/sanitizer_allocator_secondary.h:200 "((nearest_chunk)) < ((h->map_beg + h->map_size))" (0x7ed8e9af7000, 0x0)
    #0 0x4b061b in AsanCheckFailed /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_rtl.cpp:74
    #1 0x4cf00e in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/sanitizer_common/sanitizer_termination.cpp:78
    #2 0x41fe8e in __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback, __sanitizer::LargeMmapAllocatorPtrArrayDynamic, __sanitizer::LocalAddressSpaceView>::GetBlockBegin(void const*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/sanitizer_common/sanitizer_allocator_secondary.h:200
    #3 0x41fe8e in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >, __sanitizer::LargeMmapAllocatorPtrArrayDynamic>::GetBlockBegin(void const*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/sanitizer_common/sanitizer_allocator_combined.h:134
    #4 0x41fe8e in __asan::Allocator::GetAsanChunkByAddr(unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_allocator.cpp:793
    #5 0x41fe8e in __asan::Allocator::FindHeapChunkByAddress(unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_allocator.cpp:814
    #6 0x41fe8e in __asan::FindHeapChunkByAddress(unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_allocator.cpp:955
    #7 0x42719f in __asan::GetHeapAddressInformation(unsigned long, unsigned long, __asan::HeapAddressDescription*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_descriptions.cpp:158
    #8 0x42865d in __asan::AddressDescription::AddressDescription(unsigned long, unsigned long, bool) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_descriptions.cpp:445
    #9 0x4ae716 in __asan::AddressDescription::AddressDescription(unsigned long, bool) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_descriptions.h:207
    #10 0x4ae716 in __asan::ErrorFreeNotMalloced::ErrorFreeNotMalloced(unsigned int, __sanitizer::BufferedStackTrace*, unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_errors.h:107
    #11 0x4ae716 in __asan::ReportFreeNotMalloced(unsigned long, __sanitizer::BufferedStackTrace*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_report.cpp:237
    #12 0x4aa1d7 in operator delete[](void*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_new_delete.cpp:163
    #13 0x888139 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /dss/dsshome1/lrz/sys/spack/release/22.2.0/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/shared_ptr_base.h:168
    #14 0x888139 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /dss/dsshome1/lrz/sys/spack/release/22.2.0/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/shared_ptr_base.h:705
    #15 0x888139 in std::__shared_ptr<double, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /dss/dsshome1/lrz/sys/spack/release/22.2.0/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/shared_ptr_base.h:1154
    #16 0x888139 in std::__shared_ptr<double, (__gnu_cxx::_Lock_policy)2>::operator=(std::__shared_ptr<double, (__gnu_cxx::_Lock_policy)2>&&) /dss/dsshome1/lrz/sys/spack/release/22.2.0/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/shared_ptr_base.h:1250
    #17 0x888139 in std::shared_ptr<double>::operator=(std::shared_ptr<double>&&) /dss/dsshome1/lrz/sys/spack/release/22.2.0/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/shared_ptr.h:385
    #18 0x888139 in easi::Matrix<double>::clear() /hppfs/scratch/0A/di73yeq4/tmp/x86_avx512/spack-stage-easi-1.2.0-33zv2etwlz5cgiuxuezdnwknss2alrbj/spack-src/include/easi/util/Matrix.h:57
    #19 0x888139 in easi::Query::clear() /hppfs/scratch/0A/di73yeq4/tmp/x86_avx512/spack-stage-easi-1.2.0-33zv2etwlz5cgiuxuezdnwknss2alrbj/spack-src/src/Query.cpp:23
    #20 0x88820b in easi::Query::~Query() /hppfs/scratch/0A/di73yeq4/tmp/x86_avx512/spack-stage-easi-1.2.0-33zv2etwlz5cgiuxuezdnwknss2alrbj/spack-src/src/Query.cpp:14
    #21 0x89792b in easi::Composite::evaluate(easi::Query&, easi::ResultAdapter&) /hppfs/scratch/0A/di73yeq4/tmp/x86_avx512/spack-stage-easi-1.2.0-33zv2etwlz5cgiuxuezdnwknss2alrbj/spack-src/src/component/Composite.cpp:116
    #22 0x8a242f in easi::Switch::evaluate(easi::Query&, easi::ResultAdapter&) /hppfs/scratch/0A/di73yeq4/tmp/x86_avx512/spack-stage-easi-1.2.0-33zv2etwlz5cgiuxuezdnwknss2alrbj/spack-src/src/component/Switch.cpp:46
    #23 0x5c8cce in seissol::initializers::MaterialParameterDB<seissol::model::Plasticity>::evaluateModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, seissol::initializers::QueryGenerator const&) (/hppfs/work/pr63qo/di73yeq4/SeisSol/build-gcc/SeisSol_Debug_dskx_4_elastic+0x5c8cce)
    #24 0x6ce82b in seissol::Interoperability::initializeModel(char*, bool, bool, bool, bool, double*, double*, double*, double*, double*) /hppfs/work/pr63qo/di73yeq4/SeisSol/src/Solver/Interoperability.cpp:672
    #25 0x6cc411 in c_interoperability_initializeModel /hppfs/work/pr63qo/di73yeq4/SeisSol/src/Solver/Interoperability.cpp:155
    #26 0x733a69 in __ini_model_mod_MOD_ini_model /hppfs/work/pr63qo/di73yeq4/SeisSol/src/Physics/ini_model.f90:142
    #27 0x6903d4 in __ini_seissol_mod_MOD_ini_seissol /hppfs/work/pr63qo/di73yeq4/SeisSol/src/Initializer/ini_seissol.f90:276
    #28 0x68de03 in fortran_main /hppfs/work/pr63qo/di73yeq4/SeisSol/src/seissolxx.f90:184
    #29 0x4ea173 in main /hppfs/work/pr63qo/di73yeq4/SeisSol/src/main.cpp:76
    #30 0x7f087c9a32bc in __libc_start_main (/lib64/libc.so.6+0x352bc)
    #31 0x41e2f9 in _start (/hppfs/work/pr63qo/di73yeq4/SeisSol/build-gcc/SeisSol_Debug_dskx_4_elastic+0x41e2f9)
````

2 another run on 2 nodes
```bash
Mon Sep 05 12:45:38, Info:  Reading mesh. Done. 
Mon Sep 05 12:45:38, Info:  Extracting fault information 
Mon Sep 05 12:45:39, Info:  Mesh initialized in: 75.294 (min: 75.294, max: 75.2941)
=================================================================
==1590314==AddressSanitizer CHECK failed: /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/sanitizer_common/sanitizer_allocator_secondary.h:200 "((nearest_chunk)) < ((h->map_beg + h->map_size))" (0x7f077ee91000, 0x0)
    #0 0x4b061b in AsanCheckFailed /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_rtl.cpp:74
    #1 0x4cf00e in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/sanitizer_common/sanitizer_termination.cpp:78
    #2 0x41fe8e in __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback, __sanitizer::LargeMmapAllocatorPtrArrayDynamic, __sanitizer::LocalAddressSpaceView>::GetBlockBegin(void const*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/sanitizer_common/sanitizer_allocator_secondary.h:200
    #3 0x41fe8e in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >, __sanitizer::LargeMmapAllocatorPtrArrayDynamic>::GetBlockBegin(void const*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/sanitizer_common/sanitizer_allocator_combined.h:134
    #4 0x41fe8e in __asan::Allocator::GetAsanChunkByAddr(unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_allocator.cpp:793
    #5 0x41fe8e in __asan::Allocator::FindHeapChunkByAddress(unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_allocator.cpp:814
    #6 0x41fe8e in __asan::FindHeapChunkByAddress(unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_allocator.cpp:955
    #7 0x42719f in __asan::GetHeapAddressInformation(unsigned long, unsigned long, __asan::HeapAddressDescription*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_descriptions.cpp:158
    #8 0x42865d in __asan::AddressDescription::AddressDescription(unsigned long, unsigned long, bool) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_descriptions.cpp:445
    #9 0x4ae716 in __asan::AddressDescription::AddressDescription(unsigned long, bool) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_descriptions.h:207
    #10 0x4ae716 in __asan::ErrorFreeNotMalloced::ErrorFreeNotMalloced(unsigned int, __sanitizer::BufferedStackTrace*, unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_errors.h:107
    #11 0x4ae716 in __asan::ReportFreeNotMalloced(unsigned long, __sanitizer::BufferedStackTrace*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_report.cpp:237
    #12 0x4aa539 in operator delete(void*, unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_new_delete.cpp:172
    #13 0x6d6d15 in __gnu_cxx::new_allocator<seissol::model::Plasticity>::deallocate(seissol::model::Plasticity*, unsigned long) /dss/lrzsys/sys/spack/release/22.2.1/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/ext/new_allocator.h:145
    #14 0x6d6407 in std::allocator_traits<std::allocator<seissol::model::Plasticity> >::deallocate(std::allocator<seissol::model::Plasticity>&, seissol::model::Plasticity*, unsigned long) /dss/lrzsys/sys/spack/release/22.2.1/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/alloc_traits.h:492
    #15 0x6d5651 in std::_Vector_base<seissol::model::Plasticity, std::allocator<seissol::model::Plasticity> >::_M_deallocate(seissol::model::Plasticity*, unsigned long) /dss/lrzsys/sys/spack/release/22.2.1/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/stl_vector.h:354
    #16 0x6d3dbd in std::_Vector_base<seissol::model::Plasticity, std::allocator<seissol::model::Plasticity> >::~_Vector_base() /dss/lrzsys/sys/spack/release/22.2.1/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/stl_vector.h:335
    #17 0x6d2a8e in std::vector<seissol::model::Plasticity, std::allocator<seissol::model::Plasticity> >::~vector() /dss/lrzsys/sys/spack/release/22.2.1/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/stl_vector.h:683
    #18 0x6cea4f in seissol::Interoperability::initializeModel(char*, bool, bool, bool, bool, double*, double*, double*, double*, double*) /hppfs/work/pr63qo/di73yeq4/SeisSol/src/Solver/Interoperability.cpp:683
    #19 0x6cc411 in c_interoperability_initializeModel /hppfs/work/pr63qo/di73yeq4/SeisSol/src/Solver/Interoperability.cpp:155
    #20 0x733a69 in __ini_model_mod_MOD_ini_model /hppfs/work/pr63qo/di73yeq4/SeisSol/src/Physics/ini_model.f90:142
    #21 0x6903d4 in __ini_seissol_mod_MOD_ini_seissol /hppfs/work/pr63qo/di73yeq4/SeisSol/src/Initializer/ini_seissol.f90:276
    #22 0x68de03 in fortran_main /hppfs/work/pr63qo/di73yeq4/SeisSol/src/seissolxx.f90:184
    #23 0x4ea173 in main /hppfs/work/pr63qo/di73yeq4/SeisSol/src/main.cpp:76
    #24 0x7f371d9bd2bc in __libc_start_main (/lib64/libc.so.6+0x352bc)
    #25 0x41e2f9 in _start (/hppfs/work/pr63qo/di73yeq4/SeisSol/build-gcc/SeisSol_Debug_dskx_4_elastic+0x41e2f9)
```
the other run
```bash
Mon Sep 05 13:39:20, Info:  Reading mesh. Done. 
Mon Sep 05 13:39:20, Info:  Extracting fault information 
Mon Sep 05 13:39:20, Info:  Mesh initialized in: 75.4311 (min: 75.4089, max: 75.4533)
=================================================================
==958873==AddressSanitizer CHECK failed: /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/sanitizer_common/sanitizer_allocator_secondary.h:200 "((nearest_chunk)) < ((h->map_beg + h->map_size))" (0x7f86b1373000, 0x0)
    #0 0x4b061b in AsanCheckFailed /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_rtl.cpp:74
    #1 0x4cf00e in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/sanitizer_common/sanitizer_termination.cpp:78
    #2 0x41fe8e in __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback, __sanitizer::LargeMmapAllocatorPtrArrayDynamic, __sanitizer::LocalAddressSpaceView>::GetBlockBegin(void const*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/sanitizer_common/sanitizer_allocator_secondary.h:200
    #3 0x41fe8e in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >, __sanitizer::LargeMmapAllocatorPtrArrayDynamic>::GetBlockBegin(void const*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/sanitizer_common/sanitizer_allocator_combined.h:134
    #4 0x41fe8e in __asan::Allocator::GetAsanChunkByAddr(unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_allocator.cpp:793
    #5 0x41fe8e in __asan::Allocator::FindHeapChunkByAddress(unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_allocator.cpp:814
    #6 0x41fe8e in __asan::FindHeapChunkByAddress(unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_allocator.cpp:955
    #7 0x42719f in __asan::GetHeapAddressInformation(unsigned long, unsigned long, __asan::HeapAddressDescription*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_descriptions.cpp:158
    #8 0x42865d in __asan::AddressDescription::AddressDescription(unsigned long, unsigned long, bool) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_descriptions.cpp:445
    #9 0x4ae716 in __asan::AddressDescription::AddressDescription(unsigned long, bool) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_descriptions.h:207
    #10 0x4ae716 in __asan::ErrorFreeNotMalloced::ErrorFreeNotMalloced(unsigned int, __sanitizer::BufferedStackTrace*, unsigned long) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_errors.h:107
    #11 0x4ae716 in __asan::ReportFreeNotMalloced(unsigned long, __sanitizer::BufferedStackTrace*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_report.cpp:237
    #12 0x4aa1d7 in operator delete[](void*) /tmp/di39lit/x86_64/spack-stage-gcc-11.2.0-bmnv5vksvdigbsjjoqkahdblfkwvpy5r/spack-src/libsanitizer/asan/asan_new_delete.cpp:163
    #13 0x89a9d9 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /dss/dsshome1/lrz/sys/spack/release/22.2.0/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/shared_ptr_base.h:168
    #14 0x89a9d9 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::operator=(std::__shared_count<(__gnu_cxx::_Lock_policy)2> const&) /dss/dsshome1/lrz/sys/spack/release/22.2.0/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/shared_ptr_base.h:724
    #15 0x89a9d9 in std::__shared_ptr<double, (__gnu_cxx::_Lock_policy)2>::operator=(std::__shared_ptr<double, (__gnu_cxx::_Lock_policy)2> const&) /dss/dsshome1/lrz/sys/spack/release/22.2.0/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/shared_ptr_base.h:1153
    #16 0x89a9d9 in std::shared_ptr<double>::operator=(std::shared_ptr<double> const&) /dss/dsshome1/lrz/sys/spack/release/22.2.0/opt/x86_64/gcc/11.2.0-gcc-bmnv5vk/include/c++/11.2.0/bits/shared_ptr.h:359
    #17 0x89a9d9 in easi::Matrix<double>::operator=(easi::Matrix<double> const&) /hppfs/scratch/0A/di73yeq4/tmp/x86_avx512/spack-stage-easi-1.2.0-33zv2etwlz5cgiuxuezdnwknss2alrbj/spack-src/include/easi/util/Matrix.h:11
    #18 0x89a9d9 in easi::EvalModel::evaluate(easi::Query&, easi::ResultAdapter&) /hppfs/scratch/0A/di73yeq4/tmp/x86_avx512/spack-stage-easi-1.2.0-33zv2etwlz5cgiuxuezdnwknss2alrbj/spack-src/src/component/EvalModel.cpp:20
    #19 0x8978f3 in easi::Composite::evaluate(easi::Query&, easi::ResultAdapter&) /hppfs/scratch/0A/di73yeq4/tmp/x86_avx512/spack-stage-easi-1.2.0-33zv2etwlz5cgiuxuezdnwknss2alrbj/spack-src/src/component/Composite.cpp:110
    #20 0x8a242f in easi::Switch::evaluate(easi::Query&, easi::ResultAdapter&) /hppfs/scratch/0A/di73yeq4/tmp/x86_avx512/spack-stage-easi-1.2.0-33zv2etwlz5cgiuxuezdnwknss2alrbj/spack-src/src/component/Switch.cpp:46
    #21 0x5c8cce in seissol::initializers::MaterialParameterDB<seissol::model::Plasticity>::evaluateModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, seissol::initializers::QueryGenerator const&) (/hppfs/work/pr63qo/di73yeq4/SeisSol/build-gcc/SeisSol_Debug_dskx_4_elastic+0x5c8cce)
    #22 0x6ce82b in seissol::Interoperability::initializeModel(char*, bool, bool, bool, bool, double*, double*, double*, double*, double*) /hppfs/work/pr63qo/di73yeq4/SeisSol/src/Solver/Interoperability.cpp:672
    #23 0x6cc411 in c_interoperability_initializeModel /hppfs/work/pr63qo/di73yeq4/SeisSol/src/Solver/Interoperability.cpp:155
    #24 0x733a69 in __ini_model_mod_MOD_ini_model /hppfs/work/pr63qo/di73yeq4/SeisSol/src/Physics/ini_model.f90:142
    #25 0x6903d4 in __ini_seissol_mod_MOD_ini_seissol /hppfs/work/pr63qo/di73yeq4/SeisSol/src/Initializer/ini_seissol.f90:276
    #26 0x68de03 in fortran_main /hppfs/work/pr63qo/di73yeq4/SeisSol/src/seissolxx.f90:184
    #27 0x4ea173 in main /hppfs/work/pr63qo/di73yeq4/SeisSol/src/main.cpp:76
    #28 0x7fb65772a2bc in __libc_start_main (/lib64/libc.so.6+0x352bc)
    #29 0x41e2f9 in _start (/hppfs/work/pr63qo/di73yeq4/SeisSol/build-gcc/SeisSol_Debug_dskx_4_elastic+0x41e2f9)
```

**Expected behavior**
no crash

**To Reproduce**
1. master 1a7c1ac71cd47a3737c771ed3f3e2aceb9e36607
2. seissol-env/develop-gcc11-impi-t7p,  SeisSol_Debug_dskx_4_elastic (I used the following change for asagi to work with debug:
```diff
diff --git a/src/Reader/AsagiModule.cpp b/src/Reader/AsagiModule.cpp
index f94da6ed..4e75e290 100644
--- a/src/Reader/AsagiModule.cpp
+++ b/src/Reader/AsagiModule.cpp
@@ -68,6 +68,7 @@ seissol::asagi::AsagiModule::AsagiModule()
 seissol::asagi::MPI_Mode seissol::asagi::AsagiModule::getMPIMode()
 {
 #ifdef USE_MPI
+    return MPI_OFF;
        std::string mpiModeName = utils::Env::get(ENV_MPI_MODE, "WINDOWS");
        if (mpiModeName == "WINDOWS")
                return MPI_WINDOWS;
```

3.  supermuc NG

**Comment by davschneller** [comment]
Hi, is the bug here still an issue after https://github.com/SeisSol/easi/issues/10 has been solved?

**Comment by Thomas-Ulrich** [comment]
I can confirm the bug has been fixed. Thank you!
