### ISSUE TITLE
tornado

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#94]
Hi, 
on NG, somehow, I could not find a python module with 'tornado' which is need for the installation (of at least relWithDebInfo). 

```
./generated_code/generate.py --equations elastic --matricesDir generated_code/matrices --outputDir build/build_relWithDebInfo_generatedKernels_dskx_hybrid_none_9_3/generated_code --arch dskx --order 3 --numberOfMechanisms 0 --memLayout auto_tuning/config/skx.xml --multipleSimulations 1 --dynamicRuptureMethod quadrature --PlasticityMethod nb
Traceback (most recent call last):
  File "/lrz/sys/intel/studio2019_u4/intelpython3/lib/python3.6/site-packages/matplotlib/backends/backend_webagg.py", line 27, in <module>
    import tornado
ModuleNotFoundError: No module named 'tornado'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./generated_code/generate.py", line 45, in <module>
    from yateto import useArchitectureIdentifiedBy, Generator
  File "/hppfs/work/pr45fi/di73yeq4/SeisSol/generated_code/yateto/__init__.py", line 2, in <module>
    from .generator import Generator, simpleParameterSpace, parameterSpaceFromRanges
  File "/hppfs/work/pr45fi/di73yeq4/SeisSol/generated_code/yateto/generator.py", line 8, in <module>
    from .ast.visitor import ComputeOptimalFlopCount, FindIndexPermutations, FindTensors, FindPrefetchCapabilities
  File "/hppfs/work/pr45fi/di73yeq4/SeisSol/generated_code/yateto/ast/visitor.py", line 17, in <module>
    plt = pltSpec.loader.load_module()
  File "/lrz/sys/intel/studio2019_u4/intelpython3/lib/python3.6/site-packages/matplotlib/pylab.py", line 245, in <module>
    from matplotlib import cbook, mlab, pyplot as plt
  File "/lrz/sys/intel/studio2019_u4/intelpython3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "/lrz/sys/intel/studio2019_u4/intelpython3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/lrz/sys/intel/studio2019_u4/intelpython3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/lrz/sys/intel/studio2019_u4/intelpython3/lib/python3.6/site-packages/matplotlib/backends/backend_webagg.py", line 29, in <module>
    raise RuntimeError("The WebAgg backend requires Tornado.")
RuntimeError: The WebAgg backend requires Tornado.
```
Therefore I install the module manually:

on my desktop:
```
wget https://files.pythonhosted.org/packages/29/c9/7ad276f8309ddf55ead1d515e69fda2f62dde8c6a08059c7fbbc7c650478/tornado-3.2.1.tar.gz
```
copy to supermuc and install:
```
pip install . --user tornado-3.2.1.tar.gz
```
Should that go in the documentation?

**Comment by krenzland** [comment]
This is weird, tornado is a webserver.
Anyway, it's not a direct dependency of our code; so this is probably an LRZ issues?

**Comment by daisy20170101** [comment]
I switch from python/3.6 to python/3.5 and there is tornado.
